projects:
  github:
    schema:
      - https://api.github.com/graphql:
          headers:
            authorization: bearer ${GITHUB_ACCESS_TOKEN}
# The following is required for running via the VSCode extension, but the env variable
# is not being read so it's broken. Also the schema for the previous part needs to be
# fixed.
# https://github.com/kamilkisiela/graphql-config/issues/765
# extensions:
#   endpoints:
#     default:
#       url: "https://api.github.com/graphql"
#       headers:
#         authorization: bearer ${GITHUB_ACCESS_TOKEN}
