plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  next-sitemap@*:
    dependencies:
      "@next/env": "*"
